=== haodi19/c-Assignment4/src/demoXml.dtd
<!ELEMENT users (user+)>
<!ELEMENT user (name,age,level)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA))>
<!ELEMENT level (#PCDATA))>
<!ATTLIST user id ID #REQUIRED>

=== haodi19/c-Assignment4/src/demo2.xml
<?xml version="1.0" encoding="gbk"?>
<!DOCTYPE users SYSTEM "demoXml.dtd">
<users>
    <user id="1">
        <name>Chingching</name>
        <age>10</age>
        <level>6</level>
    </user>
    <user id="2">
        <name>Bringbring</name>
        <age>11</age>
        <level>2</level>
    </user>
</users>
